version: '3.9'
services : 
  blog-database :
    image: mongo
    ports: 
      - '27017:27017'
  blog-backend :
    build: backend/
    environment: 
      - PORT= 3000
      - MONGO_URL=mongodb://blog-database:27017
    ports:
      - '3000:3000'
    depends_on:
      - blog-database
  blog-frontend :
    build: 
      context : .
      args:
        VITE_BACKEND_URL: http://localhost:3000/api/v1
    ports:
      - '3001:80'
    depends_on:
      - blog-backend

